export const COMPANY_CATEGORIES = [
  { value: "buffet", label: "Buffet" },
  { value: "decoracao", label: "Decoração" },
  { value: "fotografia", label: "Fotografia" },
  { value: "filmagem", label: "Filmagem" },
  { value: "dj", label: "DJ" },
  { value: "banda", label: "Banda Musical" },
  { value: "cantor", label: "Cantor / Música ao Vivo" },
  { value: "cerimonialista", label: "Cerimonialista" },
  { value: "assessoria-eventos", label: "Assessoria de Eventos" },
  { value: "espaco-eventos", label: "Espaço para Eventos" },
  { value: "chacara", label: "Chácara para Eventos" },
  { value: "salao-festas", label: "Salão de Festas" },
  { value: "som-iluminacao", label: "Som e Iluminação" },
  { value: "painel-led", label: "Painel de LED" },
  { value: "bartender", label: "Bartender" },
  { value: "garcom", label: "Garçom" },
  { value: "doces-bolos", label: "Doces e Bolos" },
  { value: "lembrancinhas", label: "Lembrancinhas" },
  { value: "convites-papelaria", label: "Convites e Papelaria" },
  { value: "locacao-brinquedos", label: "Locação de Brinquedos" },
  { value: "animacao-infantil", label: "Animação Infantil" },
  { value: "locacao-moveis", label: "Locação de Móveis" },
  { value: "locacao-utensilios", label: "Locação de Utensílios" },
  { value: "seguranca", label: "Segurança para Eventos" },
  { value: "recepcionista", label: "Recepcionista" },
  { value: "transporte", label: "Transporte para Eventos" },
  { value: "fogos", label: "Fogos de Artifício" },
  { value: "cabine-fotos", label: "Cabine de Fotos" },
  { value: "totem-fotografico", label: "Totem Fotográfico" },
  { value: "maquiagem", label: "Maquiagem" },
  { value: "penteado", label: "Penteado" },
  { value: "outros", label: "Outros" },
];